name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          token: ${{ secrets.SAURONECHO_WEB_ACTIONS }}
          target_branch: 'gh-pages'



